### ISSUE TITLE
TRU Covariance Matrix calculation 

### ISSUE THREAD

**Issue by draculayuan** [yaojieliu/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing#9]
Hi, thanks for the code!

I encountered an issue when reading the TRU implementation. I notice that during the calculation of Covariance Matrix, mean value "mu" were not subtracted from x_sub and x_sub_t before performing multiplication. It seems to be different from the original paper where "mu" needs to be subtracted to get the correct Covariance Matrix.

Could you help to shed some lights on this issue?

**Comment by yaojieliu** [comment]
Thanks for noticing! This is a re-implementation of the original code in tf2 to make it more readable, so we didn't go through a thorough check. I just push an update to correct the bug. Sorry for the inconvenience.
